name: Go
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18 ğŸ› ï¸
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
        id: go
      - name: Get the code ğŸ˜¤
        uses: actions/checkout@v1
      - name: Test ğŸƒâ€â™€ï¸
        run: go test -v ./...
